load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "studio.perf-logger",
    iml_files = ["perf-logger.iml"],
    test_srcs = [
        "src/main/java",
        "src/test/java",
    ],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "@intellij//:intellij-sdk",
        "//prebuilts/studio/intellij-sdk:com.intellij.java",
        "//tools/adt/idea/.idea/libraries:junit4[test]",
        "//tools/base/testutils:studio.android.sdktools.testutils[test]",
        "//tools/adt/idea/.idea/libraries:truth[test]",
        "//tools/base/annotations:studio.android.sdktools.android-annotations[test]",
        "//tools/base/common:studio.android.sdktools.common[test]",
    ],
)
